obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.35, -0.35], [0.35, -0.35], [0.35, 0.35], [-0.35, 0.35]]
inflation_radius: 0.55
cost_scaling_factor: 10.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: sensor_laser, data_type: LaserScan, topic: /m2wr/laser/scan, marking: true, clearing: true}

