local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  transform_tolerance: 0.5

  obstacle_layer:
    enabled: true
    obstacle_range: 2.5
    raytrace_range: 3.0
    max_obstacle_height: 2.0
    origin_z: 0.0
    z_resolution: 0.2
    z_voxels: 2
    unknown_threshold: 15
    mark_threshold: 0
    combination_method: 1
    track_unknown_space: true
    observation_sources: scan
    scan:
      topic: scan
      sensor_frame: base_scan
      data_type: LaserScan
      clearing: true
      marking: true
      obstacle_range: 2.5
      raytrace_range: 3.0
      inf_is_valid: true

  inflation_layer:
    enabled: true
    inflation_radius: 0.55
    cost_scaling_factor: 10.0
